# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59850fd0fa6d1101b379ebac750c37cbd3c2252eda2d0a373e99a18930d17dd9e0d4c1a82d8c8c5ca8c7150b23342779a740568a91aa7b8eddd6479f1c230c34

test:
  secret_key_base: ba984dfcb4b4f129d1a5288c119cc986dc12a76d32bc386a27c7e1eb43a4ca5b82f7430e639722ca49eeb3f26e5e20a0682d742cd9c7b70aad4158484ebaf594

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
